### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by lbnv** [quamplex/geonkick#13] opened 2023-12-11 04:23 UTC
Hi,

1. FLStudio 20.9.2 finds the plugin but cannot detect its type (effect/instrument). When I check "instrument" and try to load it the error occurs:  

`Entry point not found in proc DllMain in DLL library "C:\Program Files\Geonkick\libharfbuzz-0.dll"`

2. Reaper 6 don't see VST3, I can find LV2i only (both 2 ch. and multichannel). When I try to load it, the same error appears:

`Entry point not found in proc DllMain in DLL library "C:\Program Files\Geonkick\libharfbuzz-0.dll"`

**C:\Program Files\Geonkick\libharfbuzz-0.dll exists.**

I've tried to uninstall and install the previous version (3.0.1) with the same effect.

Windows 10.

EDIT: I excluded "C:\Program Files\Geonkick\" in my antivirus as it could produce such problems. No effect.

**Comment by iurienistor** [comment] 2023-12-11 06:50
@lbnv What is your system type? Are you running 32-bit Windows?

**Comment by lbnv** [comment] 2023-12-11 07:19
Windows 64

**Comment by iurienistor** [comment] 2023-12-11 07:50
@lbnv  Please, could you archive the C:\Program Files\Geonkick folder and attach it here? Also this folder C:\Program Files\Common Files\VST3\Geonkick.vst3

**Comment by lbnv** [comment] 2023-12-11 10:48
[Geonkick.vst3.zip](https://github.com/Geonkick-Synthesizer/geonkick/files/13634333/Geonkick.vst3.zip)
[Geonkick.zip](https://github.com/Geonkick-Synthesizer/geonkick/files/13634335/Geonkick.zip)
"Geonkick.zip" from Program Files.

**Comment by iurienistor** [comment] 2023-12-11 15:45
@lbnv thanks, I can run the plugin in reaper with these files, they are ok, it might be due to a conflict or a version mismatch... Anyway, I am planning to link statically these files, thus, no more to install them, but for now the msys environment has some strange roblems relating to building them statically.

**Comment by iurienistor** [comment] 2023-12-16 07:29
I have tested on several Windows machines the latest version of Geonkick, no problems with latest hosts like FL Studio, Ableton, Reaper, Bitwig, Ardour. Here also someone else tested and confirms that are ok for Bitwig 5, Cubase 11, Live 11, Reaper 7 and Reason 12. (https://github.com/Geonkick-Synthesizer/geonkick/issues/12#issuecomment-1849731661 ). Thus, I'll close this issue because I cannot reproduce.

@lbnv I this still reproduce, I think is the same problem as in this issue: https://github.com/Geonkick-Synthesizer/geonkick/issues/15

**Closed as completed by iurienistor** 2023-12-16 07:29 UTC
Labels: duplicate
